version: '3'
services:

  jupyterhub:
    build: jupyterhub                # Build the container from this folder.
    container_name: jupyterhub_hub   # The service will use this container name.
    volumes:                         # Give access to Docker socket.
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_data:/srv/jupyterhub
    environment:                     # Env variables passed to the Hub process.
      DOCKER_JUPYTER_IMAGE: jupyterlab_img
      DOCKER_NETWORK_NAME: ${COMPOSE_PROJECT_NAME}_default
      HUB_IP: jupyterhub_hub
    ports:
      - "8082:8000"
    restart: on-failure

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab-throwaway
    command: echo
