version: '3.7'

# Before jupyterhub spawner can launch anything,
# the host needs to be a docker swarm manager

services:
  jupyterhub:
    image: swarmspawner:3.1.1 # build from Dockerfile here https://github.com/ucphhpc/SwarmSpawner
    container_name: jupyterhub
    ports:
      - "8888:8000/tcp"
    volumes:
      - ./jupyterhub_data/jupyterhub_config_cadethub.py:/srv/jupyterhub/jupyter_config.py:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command: jupyterhub -f /srv/jupyterhub/jupyter_config.py

networks:
  default:
    name: cadethub_default
    driver: overlay
