#!/usr/bin/env bash

source .env

fn_help(){
    echo "jhub: Script to manage docker-composed jupyterhub setup"
    echo "-----"
    echo "USAGE: ./jhub [FLAGS]"
    echo "FLAGS: "
    echo "       --nuke-user-data: Remove all user data."
    echo "       -b | --build: Build images without using cache"
    echo "       -u | --up: Start containers in background. Always build images."
    echo "       -d | --down: Stop containers."

}

# Color handling
function fg () { echo -ne "\\033[0;$1m"; }
function fgx () { echo -ne "\\033[38;5;$1m"; }
function c () { echo -ne "\\033[$1m"; }

fn_nuke_user_data(){

    fg 1        # Style Bold
    fgx 1       # Color Red
    echo "Are you sure you want to NUKE USER DATA?"
    c 0         # Color End
    read -rep "continue? [y/any]: " -i "n" okay
    [ "$okay" != 'y' ] && exit

    USER_VOLUMES=$(docker volume ls -q -f "name=jupyterhub-user-")

    [ -z "$USER_VOLUMES" ] && echo "No user volumes found!" && exit

    docker volume rm $USER_VOLUMES
}

fn_up(){
    docker-compose up -d --build
}

fn_down(){
    docker-compose down
}

fn_build(){

    docker-compose build --no-cache --pull

}


POSITIONAL=()
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --nuke-user-data)
            fn_nuke_user_data
            shift
            ;;
        -b|--build)
            fn_build
            shift
            ;;
        -d|--down)
            fn_down
            shift # past value
            ;;
        -u|--up)
            fn_up
            shift # past value
            ;;
        -h|--help)
            fn_help
            shift # past value
            ;;
        *)    # unknown option
            POSITIONAL+=("$1") # save it in an array for later
            shift # past argument
            ;;
    esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters
