# TODO: needs the full building chain with swarmspawner coming from https://github.com/ucphhpc/SwarmSpawner

# Do not forget to pin down the version
FROM swarmspawner:3.1.1

# Install dependencies (for advanced authentication and spawning)
RUN pip install \
    jupyterhub-idle-culler==1.2.1 \
    jupyterhub-firstuseauthenticator==1.0.0
